# Session
allow_cloning no

# Window and platform
remember_window_size no
initial_window_width 120c
initial_window_height 30c
placement_strategy center
window_padding_width 1
resize_in_steps yes
disable_ligatures always

# macOS platform
macos_titlebar_color dark
macos_option_as_alt both
macos_colorspace displayp3

# Typography
font_family      family='JetBrainsMono Nerd Font Mono' style=Regular
bold_font        family='JetBrainsMono Nerd Font Mono' style=Bold
italic_font      family='JetBrainsMono Nerd Font Mono' style='Italic'
bold_italic_font family='JetBrainsMono Nerd Font Mono' style='Bold Italic'
symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF,U+100000-U+10ffff JetBrainsMonoNL Nerd Font
font_size 14.0
modify_font cell_height 114%
modify_font cell_width 94%
modify_font baseline 95%

# tmux-first behavior
shell $HOME/.config/kitty/start-tmux.zsh
scrollback_lines 10000
scrollbar never
tab_bar_style hidden

# BEGIN_KITTY_THEME
# Gruvbox Dark
include kitty-theme.conf
# END_KITTY_THEME

# Key bindings
clear_all_shortcuts yes

map cmd+q quit

map cmd+c copy_or_noop
map cmd+v paste_from_clipboard

map shift+enter send_text all \x1b[13;2u

map cmd+n new_os_window
map cmd+shift+n launch --type=os-window -- $HOME/.config/kitty/switch-tmux-session.zsh

map cmd+' send_text all \x11w
map cmd+o send_text all \x11[
map cmd+t send_text all \x11c
map cmd+d send_text all \x11%
map shift+cmd+d send_text all \x11"
map cmd+w send_text all \x11x
map shift+cmd+w send_text all \x11&

map cmd+1 send_text all \x111
map cmd+2 send_text all \x112
map cmd+3 send_text all \x113
map cmd+4 send_text all \x114
map cmd+5 send_text all \x115
map cmd+6 send_text all \x116
map cmd+7 send_text all \x117
map cmd+8 send_text all \x118
map cmd+9 send_text all \x119

map shift+cmd+[ send_text all \x11p
map alt+cmd+[ send_text all \x11P
map shift+cmd+] send_text all \x11n
map alt+cmd+] send_text all \x11N
