shell $HOME/.config/kitty/start-zellij

# window
remember_window_size no
initial_window_width 120c
initial_window_height 30c
placement_strategy center
window_padding_width 1
resize_in_steps yes
# tab_bar_style hidden
scrollback_lines 100000

# macOS
macos_titlebar_color dark
macos_option_as_alt both
macos_colorspace displayp3

# typography
font_size 14.0
font_family      family='JetBrainsMono Nerd Font Mono' style=Regular features='+zero +cv01 +cv03 +cv09 +cv14'
bold_font        family='JetBrainsMono Nerd Font Mono' style=Bold features='+zero +cv01 +cv03 +cv09 +cv14'
italic_font      family='JetBrainsMono Nerd Font Mono' style='Italic' features='+zero +cv01 +cv03 +cv09 +cv14'
bold_italic_font family='JetBrainsMono Nerd Font Mono' style='Bold Italic' features='+zero +cv01 +cv03 +cv09 +cv14'
symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF,U+100000-U+10ffff JetBrainsMonoNL Nerd Font
modify_font cell_height 114%
modify_font cell_width 94%
modify_font baseline 95%

# BEGIN_KITTY_THEME
# Gruvbox Dark
include kitty-theme.conf
# END_KITTY_THEME

confirm_os_window_close 0

# shortcuts
clear_all_shortcuts yes
map cmd+q quit
map cmd+n new_os_window
map cmd+v paste_from_clipboard
map cmd+, edit_config_file
map cmd+shift+, load_config_file
