shell /opt/homebrew/bin/fish

# Window
remember_window_size no
initial_window_width 120c
initial_window_height 30c
placement_strategy center
window_padding_width 1
resize_in_steps yes
# tab_bar_style hidden
scrollback_lines 100000

# macOS
macos_titlebar_color dark
macos_option_as_alt both
macos_colorspace displayp3

# Typography
# Distinct code glyphs: slashed zero and clearer l, g, f, and dollar sign.
font_size 14.0
font_family      family='JetBrainsMono Nerd Font Mono' style=Regular features='+zero +cv01 +cv03 +cv09 +cv14'
bold_font        family='JetBrainsMono Nerd Font Mono' style=Bold features='+zero +cv01 +cv03 +cv09 +cv14'
italic_font      family='JetBrainsMono Nerd Font Mono' style='Italic' features='+zero +cv01 +cv03 +cv09 +cv14'
bold_italic_font family='JetBrainsMono Nerd Font Mono' style='Bold Italic' features='+zero +cv01 +cv03 +cv09 +cv14'
symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF,U+100000-U+10ffff JetBrainsMonoNL Nerd Font
modify_font cell_height 114%
modify_font cell_width 94%
modify_font baseline 95%

# BEGIN_KITTY_THEME
# Gruvbox Dark
include kitty-theme.conf
# END_KITTY_THEME

clear_all_shortcuts yes
