#!/bin/sh

if /opt/homebrew/bin/zellij list-sessions --short 2>/dev/null \
    | /usr/bin/grep -Fxq main \
  && /opt/homebrew/bin/zellij --session main action list-clients 2>/dev/null \
    | /usr/bin/sed '1d' \
    | /usr/bin/grep -q .
then
  exec /opt/homebrew/bin/zellij
else
  exec /opt/homebrew/bin/zellij options \
    --attach-to-session true \
    --session-name main
fi
