vim.cmd("cnoreabbrev W w")
vim.cmd("cnoreabbrev Q q")
vim.cmd("cnoreabbrev Wq wq")
vim.cmd("cnoreabbrev wQ wq")
vim.cmd("cnoreabbrev WQ wq")
vim.cmd("cnoreabbrev Wa wa")
vim.cmd("cnoreabbrev wA wa")
vim.cmd("cnoreabbrev WA wa")
vim.cmd("cnoreabbrev Qa qa")
vim.cmd("cnoreabbrev qA qa")
vim.cmd("cnoreabbrev QA qa")

vim.keymap.set("n", "]t", "<Cmd>tabn<CR>")
vim.keymap.set("n", "[t", "<Cmd>tabp<CR>")
vim.keymap.set("n", "<ESC>", "<Cmd>noh<CR>")
